export const chatHistory = [
    { name: "Alice", text: "Hey, Bob! How's it going?", time: "10:00 AM", sender: true },
    { name: "Bob", text: "Hey, Alice! Doing well, thanks. How about you?", time: "10:01 AM", sender: false, profilePicture: true },
    { name: "Alice", text: "I'm good, just finishing up some work.", time: "10:02 AM", sender: true },
    { name: "Bob", text: "Sounds productive! What are you working on?", time: "10:03 AM", sender: false, profilePicture: true },
    { name: "Alice", text: "Just some coding tasks for a project. It's coming along.", time: "10:04 AM", sender: true },
    { name: "Bob", text: "Nice! Let me know if you need any help.", time: "10:05 AM", sender: false, profilePicture: true },
    { name: "Alice", text: "Thanks, will do!", time: "10:06 AM", sender: true },
    { name: "Bob", text: "Are you free later to catch up?", time: "10:07 AM", sender: false, profilePicture: true },
    { name: "Alice", text: "Yeah, I'd love that. What time?", time: "10:08 AM", sender: true },
    { name: "Bob", text: "How about 4 PM?", time: "10:09 AM", sender: false, profilePicture: true },
    { name: "Alice", text: "Perfect, see you then!", time: "10:10 AM", sender: true },
    { name: "Bob", text: "Looking forward to it!", time: "10:11 AM", sender: false, profilePicture: true },
    { name: "Alice", text: "Hey, Bob! Any update on that book recommendation?", time: "11:00 AM", sender: true },
    { name: "Bob", text: "Oh yes! You have to check out 'The Alchemist.'", time: "11:01 AM", sender: false, profilePicture: true },
    { name: "Alice", text: "I've heard good things. Adding it to my list!", time: "11:02 AM", sender: true },
    { name: "Bob", text: "You’ll love it. Very inspiring story!", time: "11:03 AM", sender: false, profilePicture: true },
    { name: "Alice", text: "Thanks for the tip!", time: "11:04 AM", sender: true },
    { name: "Bob", text: "Anytime, Alice!", time: "11:05 AM", sender: false, profilePicture: true },
    { name: "Alice", text: "Did you hear about the new cafe nearby?", time: "12:00 PM", sender: true },
    { name: "Bob", text: "No, tell me more!", time: "12:01 PM", sender: false, profilePicture: true },
    { name: "Alice", text: "It’s called The Cozy Bean. Really chill vibe.", time: "12:02 PM", sender: true },
    { name: "Bob", text: "Sounds awesome! We should go sometime.", time: "12:03 PM", sender: false, profilePicture: true },
    { name: "Alice", text: "Definitely! Maybe this weekend?", time: "12:04 PM", sender: true },
    { name: "Bob", text: "Let's do it!", time: "12:05 PM", sender: false, profilePicture: true },
    { name: "Alice", text: "Great, I’ll send you the details.", time: "12:06 PM", sender: true },
    { name: "Bob", text: "Perfect. Looking forward to it!", time: "12:07 PM", sender: false, profilePicture: true },
    { name: "Alice", text: "Hey, can you review my code when you have time?", time: "1:00 PM", sender: true },
    { name: "Bob", text: "Of course! Send it over.", time: "1:01 PM", sender: false, profilePicture: true },
    { name: "Alice", text: "Sent! Thanks so much.", time: "1:02 PM", sender: true },
    { name: "Bob", text: "No problem. I’ll take a look.", time: "1:03 PM", sender: false, profilePicture: true },
    { name: "Alice", text: "Awesome, much appreciated!", time: "1:04 PM", sender: true },
    { name: "Bob", text: "All done! Just a few minor tweaks.", time: "1:30 PM", sender: false, profilePicture: true },
    { name: "Alice", text: "Thanks for the feedback!", time: "1:31 PM", sender: true },
    { name: "Bob", text: "Anytime, Alice. Happy to help.", time: "1:32 PM", sender: false, profilePicture: true },
    { name: "Alice", text: "What’s your favorite coding language?", time: "2:00 PM", sender: true },
    { name: "Bob", text: "JavaScript, without a doubt!", time: "2:01 PM", sender: false, profilePicture: true },
    { name: "Alice", text: "Solid choice!", time: "2:02 PM", sender: true },
    { name: "Bob", text: "What about you?", time: "2:03 PM", sender: false, profilePicture: true },
    { name: "Alice", text: "I’d say Python. Love its simplicity.", time: "2:04 PM", sender: true },
    { name: "Bob", text: "Good one! So versatile.", time: "2:05 PM", sender: false, profilePicture: true },
    { name: "Alice", text: "Absolutely. Fun conversation!", time: "2:06 PM", sender: true },
    { name: "Bob", text: "Agreed! Let’s do this more often.", time: "2:07 PM", sender: false, profilePicture: true },
    { name: "Alice", text: "Yes, let’s!", time: "2:08 PM", sender: true },
    { name: "Bob", text: "Catch you later, Alice!", time: "2:09 PM", sender: false, profilePicture: true },
    { name: "Alice", text: "Bye, Bob! Take care.", time: "2:10 PM", sender: true },
  ];
  
  